### PR TITLE
Build fastbootd for recovery

### PR DESCRIPTION
**Pull request by z3ntu**
Needed for devices with dynamic partitions.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
I think this might fit product definition better?

https://github.com/Halium/android_vendor_halium_config/blob/halium-11.0/halium.mk

**Comment by z3ntu** [comment]
@peat-psuwit I can move to https://github.com/Halium/android_vendor_halium_config/blob/halium-11.0/halium.mk#L252-L263 , does that sound good?

**Comment by peat-psuwit** [comment]
Err... ok, my bad. Further research shows that fastbootd appears more frequently in the device trees.

https://github.com/search?l=Makefile&p=3&q=org%3ALineageOS+fastbootd&type=Code

But now it got me thinking: what happens if fastbootd is included, and then the image is used on a device without a super partition?

**Comment by z3ntu** [comment]
The recovery has checks to only show fastbootd when `ro.boot.dynamic_partitions` is set, otherwise fastbootd will be inaccessible.

See e.g. this for the checks that are present in AOSP recovery (on the "minus" side): https://gerrit-public.fairphone.software/plugins/gitiles/platform/bootable/recovery/+/1a29d30bd7aafa334d1e814299178f8fdc4724e1%5E%21/#F0 (

**Comment by peat-psuwit** [comment]
And `ro.boot.dynamic_partitions` is set by `androidboot.dynamic_partitions` kernel command line... OK! Then it's probably fine to include it unconditionally. Devices that need them _probably_ have the kernel cmdline in their bootloader.

**Review by mariogrip — APPROVED** [review]

**Review by NotKit — APPROVED** [review]

**Pull request merged**
